[package]
name = "pobr-desktop"
version.workspace = true
edition.workspace = true

[lib]
name = "pobr_desktop"
path = "src/lib.rs"

[[bin]]
name = "pobr-desktop"
path = "src/main.rs"

[dependencies]
pobr-data.workspace = true
pobr-core.workspace = true
pobr-build.workspace = true
pobr-i18n.workspace = true
