/**
 * 内置配置项标签汉化（var → 简中；zh-TW 界面暂共用简中文案）。
 *
 * 英文原文来自 vendor PoB2 `ConfigOptions.lua`（overlay/config_options.json），
 * 译名尽量对齐国服/社区通行术语；个别不准的直接改本表对应行即可。
 * 渲染前先剥 `^xRRGGBB` / `^N` 颜色码（见 ConfigPanel 的 stripColorCodes）。
 */

export const CONFIG_LABEL_ZH: Record<string, string> = {
  ActiveBrands: '激活的烙印数量：',
  BlockedPast10Sec: '过去 10 秒内格挡次数',
  BrandsAttachedToEnemy: '贴附在敌人身上的烙印数量：',
  BrandsInLastHalf: '处于贴附持续时间的后 50%？',
  BrandsInLastQuarter: '处于贴附持续时间的后 25%？',
  ChanceToIgnoreEnemyPhysicalDamageReductionMode: '无视敌人物理减伤几率的计算模式：',
  ChillStacks: '冰缓层数',
  ColdSnapBypassCD: '绕过冷却？',
  ConcPathBypassCD: '绕过冷却？',
  DetonatedMinesRecently: '最近引爆过地雷？',
  DisableEHPGainOnBlock: '格挡/压制不计入有效生命：',
  EEIgnoreHitDamage: '忽略技能击中伤害？',
  EHPUnluckyWorstOf: '有效生命计算取不幸口径：',
  EVBypass: '禁用帝王的警觉绕过',
  EverlastingSacrifice: '拥有永恒献祭？',
  FlickerStrikeBypassCD: '绕过冷却？',
  GamblesprintMovementSpeed: '赌命疾奔移动速度',
  HoarfrostStacks: '白霜层数',
  LostNonVaalBuffRecently: '最近失去过非瓦尔守护技能增益？',
  MoltenShellDamageMitigated: '已减免的伤害：',
  ScorchStacks: '灼烧层数',
  SecondsSinceInevitableCrit: '距必然暴击的秒数：',
  ShockStacks: '感电层数',
  ShrapnelBallistaProjectileOverlap: '重叠命中的投射物数量：',
  TotalRadianceSentinelLife: '光辉哨兵总生命',
  TotalSpectreLife: '魅影总生命：',
  TotalTotemLife: '图腾总生命：',
  TotalVaalRejuvenationTotemLife: '瓦尔回春图腾总生命：',
  TotemsSummoned: '已召唤图腾数（非最大值时）：',
  TriggeredTrapsRecently: '最近触发过陷阱？',
  Unbound: '处于解缚状态？',
  VaalMoltenShellDamageMitigated: '已减免的伤害：',
  VigilantStrikeBypassCD: '绕过冷却？',
  absolutionSkillDamageCountedOnce: '赦罪：技能伤害只计一次',
  ailmentMode: '异常状态计算模式：',
  animateWeaponLingeringBlade: '正在激活残留之刃？',
  arcaneCloakUsedRecentlyCheck: '计入最近消耗的魔力？',
  armourCalculationMode: '护甲计算模式：',
  aspectOfTheAvianAviansFlight: '鸟之势·飞翔生效中？',
  aspectOfTheAvianAviansMight: '鸟之势·威能生效中？',
  aspectOfTheCatCatsAgility: '猫之势·敏捷生效中？',
  aspectOfTheCatCatsStealth: '猫之势·潜行生效中？',
  aspectOfTheSpiderWebStacks: '蛛网层数：',
  bannerPlanted: '战旗已插下？',
  bannerValour: '战旗勇气值：',
  barkskinStacks: '树皮层数：',
  bladestormInBloodstorm: '处于血刃风暴中？',
  bladestormInSandstorm: '处于沙刃风暴中？',
  bloodSacramentReservationEHP: '技能保留计入有效生命？',
  bloodSandStance: '姿态：',
  buffAdrenaline: '拥有肾上腺素？',
  buffAlchemistsGenius: '拥有炼金天赋？',
  buffArcaneSurge: '拥有奥术涌动？',
  buffBastionOfHope: '希望壁垒生效中？',
  buffChaoticMight: '拥有混沌之力？',
  buffConflux: '汇流增益：',
  buffDivinity: '拥有神圣化身？',
  buffElusive: '处于灵巧状态？',
  buffFanaticism: '拥有狂热？',
  buffFortification: '处于巩固状态？',
  buffHeartstopper: '摄心模式：',
  buffHerEmbrace: '处于她的拥抱中？',
  buffLifetap: '拥有生命引用？',
  buffNgamahuFlamesAdvance: '熔岩打击生效中？',
  buffOnslaught: '拥有猛攻？',
  buffPendulum: '毁灭钟摆生效中？',
  buffPhasing: '拥有相位？',
  buffQuicksandHourglass: '拥有流沙之漏？',
  buffUnholyMight: '拥有不洁之力？',
  buffVaalArcLuckyHits: '拥有瓦尔电弧的幸运增益？',
  carrionGolemEqualsChaosGolem: '腐肉魔像数 = 混沌魔像数：',
  carrionGolemNearbyMinion: '附近非魔像召唤物数量：',
  changedStance: '最近切换过姿态？',
  channellingCycloneCheck: '正在引导旋风斩？',
  chaosGolemEqualsStoneGolem: '混沌魔像数 = 石魔像数：',
  clashCondition: '敌人生命百分比高于玩家？',
  companionInPresence: '同伴在你的临在范围内？',
  conditionActiveBlockedRecently: '最近主动格挡过？',
  conditionAilmentConsumed: '吞噬过异常状态？',
  conditionAtCloseRange: '敌人处于近距离？',
  conditionAttackedRecently: '最近攻击过？',
  conditionBeenCritRecently: '最近被暴击过？',
  conditionBeenHitByAttackRecently: '最近被攻击击中过？',
  conditionBeenHitRecently: '最近被击中过？',
  conditionBeenSavageHitRecently: '最近受到过重创？',
  conditionBetweenYouAndLinkedTarget: '敌人处于你的联结光束中？',
  conditionBleedAggravated: '流血已恶化？',
  conditionBleeding: '你在流血？',
  conditionBlinded: '你被致盲？',
  conditionBlockedAttackRecently: '最近格挡过攻击？',
  conditionBlockedHitFromUniqueEnemyInPast10Sec: '过去 10 秒内格挡过传奇敌人的击中？',
  conditionBlockedRecently: '最近格挡过？',
  conditionBlockedSpellRecently: '最近格挡过法术？',
  conditionBrittle: '你处于易碎状态？',
  conditionBrittleEffect: '易碎效果：',
  conditionBurning: '你在燃烧？',
  conditionCanBeCurseImmune: '你免疫诅咒？',
  conditionCastLast1Seconds: '最近 1 秒内施放过法术？',
  conditionCastMarkRecently: '最近使用过印记？',
  conditionCastSpellRecently: '最近施放过法术？',
  conditionChampionIntimidate: '勇士的威吓生效中？',
  conditionChangedStanceLastSecond: '最近 1 秒内切换过姿态？',
  conditionChannelling: '你在引导？',
  conditionChilled: '你被冰缓？',
  conditionChilledEffect: '冰缓效果：',
  conditionChilledEnemyRecently: '最近冰缓过敌人？',
  conditionConsumed12SteelShardsRecently: '最近消耗过 12 枚钢铁碎片？',
  conditionConsumedCorpseInPast2Sec: '过去 2 秒内吞噬过尸体？',
  conditionConsumedCorpseRecently: '最近吞噬过尸体？',
  conditionConvergence: '拥有汇聚？',
  conditionCorruptingCryStages: '腐化之血层数：',
  conditionCritInPast8Sec: '过去 8 秒内暴击过？',
  conditionCritRecently: '最近暴击过？',
  conditionCritWithHeraldSkillRecently: '先驱技能最近暴击过？',
  conditionCursedEnemyRecently: '最近诅咒过敌人？',
  conditionDodgeRolledRecently: '最近翻滚闪避过？',
  conditionEmpowered: '技能处于强化状态？',
  conditionEnemyAffectedByHazardRecently: '敌人最近受到危害物影响？',
  conditionEnemyArmourBroken: '敌人护甲已破坏？',
  conditionEnemyBleeding: '敌人在流血？',
  conditionEnemyBlinded: '敌人被致盲？',
  conditionEnemyBrittle: '敌人处于易碎状态？',
  conditionEnemyBurning: '敌人在燃烧？',
  conditionEnemyChilled: '敌人被冰缓？',
  conditionEnemyChilledByYourHits: '敌人被你的击中冰缓？',
  conditionEnemyChilledEffect: '冰缓效果：',
  conditionEnemyColdExposure: '敌人处于冰霜曝露？',
  conditionEnemyColdResZero: '敌人用冰霜伤害击中过你？',
  conditionEnemyCoveredInAsh: '敌人被灰烬覆盖？',
  conditionEnemyCoveredInFrost: '敌人被冰霜覆盖？',
  conditionEnemyCriticalWeakness: '敌人处于致命弱点状态',
  conditionEnemyCrushed: '敌人被碾压？',
  conditionEnemyCursed: '敌人被诅咒？',
  conditionEnemyDazed: '敌人处于眩晕？',
  conditionEnemyDebilitated: '敌人被衰弱？',
  conditionEnemyElectrocuted: '敌人被电击瘫痪？',
  conditionEnemyExitedPresenceRecently: '敌人最近进入过临在范围？',
  conditionEnemyFireExposure: '敌人处于火焰曝露？',
  conditionEnemyFireResZero: '敌人用火焰伤害击中过你？',
  conditionEnemyFrozen: '敌人被冻结？',
  conditionEnemyFullLife: '敌人满血？',
  conditionEnemyHasOpenWeakness: '敌人有破绽？',
  conditionEnemyHaveEnergyShield: '敌人拥有能量护盾？',
  conditionEnemyHeavyStunned: '敌人处于重度晕眩？',
  conditionEnemyHindered: '敌人被阻碍？',
  conditionEnemyIgnited: '敌人被点燃？',
  conditionEnemyImmobilised: '敌人被定身？',
  conditionEnemyInChillingArea: '敌人处于冰缓区域？',
  conditionEnemyInFrostGlobe: '敌人处于冰霜护盾区域内？',
  conditionEnemyIntimidated: '敌人被威吓？',
  conditionEnemyIsolated: '敌人处于孤立状态？',
  conditionEnemyLightningExposure: '敌人处于闪电曝露？',
  conditionEnemyLightningResZero: '敌人用闪电伤害击中过你？',
  conditionEnemyLowLife: '敌人处于低血？',
  conditionEnemyMaimed: '敌人被残废？',
  conditionEnemyMoving: '敌人在移动？',
  conditionEnemyOnBrittleGround: '敌人处于易碎之地？',
  conditionEnemyOnChilledGround: '敌人处于冰缓之地？',
  conditionEnemyOnConsecratedGround: '敌人处于奉献之地？',
  conditionEnemyOnFungalGround: '敌人处于真菌之地？',
  conditionEnemyOnProfaneGround: '敌人处于亵渎之地？',
  conditionEnemyOnSappedGround: '敌人处于消耗之地？',
  conditionEnemyOnScorchedGround: '敌人处于灼烧之地？',
  conditionEnemyOnShockedGround: '敌人处于感电之地？',
  conditionEnemyPacified: '敌人被安抚？',
  conditionEnemyPinned: '敌人被钉住？',
  conditionEnemyPoisoned: '敌人中毒？',
  conditionEnemyRareOrUnique: '敌人是稀有怪？',
  conditionEnemySapped: '敌人被消耗？',
  conditionEnemyScorched: '敌人被灼烧？',
  conditionEnemyShocked: '敌人被感电？',
  conditionEnemyStunned: '敌人被晕眩？',
  conditionEnemyTaunted: '敌人被嘲讽？',
  conditionEnemyUnnerved: '敌人被慑服？',
  conditionEnergyShieldRechargePastTwoSec: '能量护盾回充在过去 2 秒内开始？',
  conditionEnergyShieldRechargeRecently: '能量护盾回充最近开始过？',
  conditionFocused: '处于专注状态？',
  conditionFreezeConsumed: '吞噬过冻结',
  conditionFrozen: '你被冻结？',
  conditionFrozenEnemyRecently: '最近冻结过敌人？',
  conditionFullEnergyShield: '总是满能量护盾？',
  conditionFullLife: '总是满血？',
  conditionFullMana: '总是满魔力？',
  conditionGainedFrenzyChargeRecently: '最近获得过狂怒球？',
  conditionGainedPowerChargeRecently: '最近获得过暴击球？',
  conditionHaveArborix: '拥有钢铁反射？',
  conditionHaveAugyre: '奥格瑞轮转增益：',
  conditionHaveEnergyShield: '总是拥有能量护盾？',
  conditionHaveManaStorm: '拥有魔力风暴增益？',
  conditionHaveTotem: '已召唤图腾？',
  conditionHaveVulconus: '拥有烈火化身？',
  conditionHitByColdDamageRecently: '最近被冰霜伤害击中过？',
  conditionHitByFireDamageRecently: '最近被火焰伤害击中过？',
  conditionHitByLightningDamageRecently: '最近被闪电伤害击中过？',
  conditionHitBySpellDamageRecently: '最近受到过法术伤害？',
  conditionHitMeleeRecently: '最近近战击中过？',
  conditionHitProjectileRecently: '最近用投射物攻击击中过？',
  conditionHitRecently: '最近击中过？',
  conditionHitRecentlyWithWeapon: '最近用武器击中过？',
  conditionHitSpellRecently: '最近用法术击中过？',
  conditionHitsAlwaysHeavyStun: '你的击中总是重度晕眩？',
  conditionHitsAlwaysStun: '你的击中总是晕眩？',
  conditionIgniteConsumed: '吞噬过点燃',
  conditionIgnited: '你被点燃？',
  conditionIgnitedEnemyRecently: '最近点燃过敌人？',
  conditionImpaledRecently: '最近穿刺过敌人？',
  conditionInDodgeRoll: '正在翻滚闪避？',
  conditionInfusionConsumedRecently: '最近消耗过灌注？',
  conditionInsane: '处于疯狂状态？',
  conditionKilledAffectedByDoT: '最近击杀过受你持续伤害影响的敌人？',
  conditionKilledLast3Seconds: '最近 3 秒内击杀过？',
  conditionKilledPoisonedLast2Seconds: '最近 2 秒内击杀过中毒的敌人？',
  conditionKilledRecently: '最近击杀过？',
  conditionKilledShockedLast3Seconds: '最近 3 秒内击杀过感电的敌人？',
  conditionKilledTauntedEnemyRecently: '最近击杀过被嘲讽的敌人？',
  conditionKilledUniqueEnemy: '最近击杀过稀有或传奇敌人？',
  conditionLeeching: '你在偷取？',
  conditionLeechingEnergyShield: '你在偷取能量护盾？',
  conditionLeechingLife: '你在偷取生命？',
  conditionLeechingMana: '你在偷取魔力？',
  conditionLinkedRecently: '最近联结过？',
  conditionLostEnduranceChargeInPast8Sec: '过去 8 秒内失去过耐力球？',
  conditionLowEnergyShield: '总是低能量护盾？',
  conditionLowLife: '总是低血？',
  conditionLowMana: '总是低魔？',
  conditionMinionsDiedRecently: '最近有召唤物死亡？',
  conditionMinionsKilledRecently: '你的召唤物最近击杀过？',
  conditionMoving: '总是在移动？',
  conditionNearLinkedTarget: '敌人靠近你的联结目标？',
  conditionNoLifeFlaskUsesLeft: '生命药剂已无使用次数？',
  conditionNonCritRecently: '最近造成过非暴击？',
  conditionOldSpear: '长矛存在超过 0.5 秒？',
  conditionOnBurningGround: '你处于燃烧之地？',
  conditionOnCausticGround: '你处于腐蚀之地？',
  conditionOnChilledGround: '你处于冰缓之地？',
  conditionOnConsecratedGround: '你处于奉献之地？',
  conditionOnFungalGround: '你处于真菌之地？',
  conditionOnIgnitedGround: '你处于点燃之地？',
  conditionOnShockedGround: '你处于感电之地？',
  conditionOpenWeaknessEnemyPresence: '临在范围内敌人有破绽？',
  conditionParriedRecently: '最近招架过？',
  conditionPinnedEnemyRecently: '最近钉住过敌人？',
  conditionPoisoned: '你中毒了？',
  conditionRavenousCorpseConsumed: '贪食已吞噬过尸体？',
  conditionReloadedRecently: '最近装填过？',
  conditionSapEffect: '消耗效果：',
  conditionSapped: '你被消耗？',
  conditionScorched: '你被灼烧？',
  conditionScorchedEffect: '灼烧效果：',
  conditionSelfChill: '冰缓过自己？',
  conditionShapeshiftToAnimal: '最近变形为动物形态？',
  conditionShapeshiftToHuman: '最近变形回人类形态？',
  conditionShapeshifted: '当前处于变形状态？',
  conditionShatteredEnemyRecently: '最近粉碎过敌人？',
  conditionShockConsumed: '吞噬过感电',
  conditionShockEffect: '感电效果（非最大值时）：',
  conditionShocked: '你被感电？',
  conditionShockedEnemyRecently: '最近感电过敌人？',
  conditionSkillCritRecently: '你的技能最近暴击过？',
  conditionSoulGainPrevention: '处于灵魂获取阻止？',
  conditionSpawnedCorpseRecently: '最近生成过尸体？',
  conditionSprinting: '正在疾跑？',
  conditionStationary: '静止不动的时长',
  conditionStoppedTakingDamageOverTimeRecently: '最近停止受到持续伤害？',
  conditionStunnedEnemyRecently: '最近晕眩过敌人？',
  conditionStunnedRecently: '最近被晕眩过？',
  conditionStunnedWhileCastingRecently: '最近施法时被晕眩过？',
  conditionSummonedGolemInPast10Sec: '过去 10 秒内召唤过魔像？',
  conditionSummonedGolemInPast8Sec: '过去 8 秒内召唤过魔像？',
  conditionSummonedSpectreInPast8Sec: '过去 8 秒内召唤过魅影？',
  conditionSummonedTotemRecently: '最近召唤过图腾？',
  conditionSummonedZombieInPast8Sec: '过去 8 秒内召唤过僵尸？',
  conditionSuppressedRecently: '最近压制过？',
  conditionSurrounded: '你被包围？',
  conditionTakenFireDamageFromEnemyHitRecently: '最近受到过敌人击中的火焰伤害？',
  conditionTauntedEnemyRecently: '最近嘲讽过敌人？',
  conditionThrownTrapOrMineRecently: '最近投掷过陷阱或地雷？',
  conditionTotemsHitRecently: '你的图腾最近击中过？',
  conditionTotemsHitSpellRecently: '你的图腾最近用法术击中过？',
  conditionTotemsKilledRecently: '你的图腾最近击杀过？',
  conditionTotemsNotSummonedInPastTwoSeconds: '过去 2 秒内未召唤图腾？',
  conditionTriggeredSkillRecently: '最近触发过技能？',
  conditionUnravelling: '侍僧的解丝：',
  conditionUsedBrandRecently: '最近使用过烙印技能？',
  conditionUsedColdSkillRecently: '最近使用过冰霜技能？',
  conditionUsedDashRecently: '最近施放过冲刺？',
  conditionUsedFireSkillRecently: '最近使用过火焰技能？',
  conditionUsedMinionSkillRecently: '最近使用过召唤物技能？',
  conditionUsedMovementSkillRecently: '最近使用过移动技能？',
  conditionUsedSkillRecently: '最近使用过技能？',
  conditionUsedTravelSkillRecently: '最近使用过位移技能？',
  conditionUsedVaalSkillRecently: '最近使用过瓦尔技能？',
  conditionUsedWarcryInPast8Seconds: '过去 8 秒内使用过战吼？',
  conditionUsedWarcryRecently: '最近使用过战吼？',
  conditionUsingCharm: '有护符生效中？',
  conditionUsingFlask: '有药剂生效中？',
  configMistRavenCount: '激活的雾鸦数量：',
  configResonanceCount: '总共鸣值：',
  configSpectralWolfCount: '激活的幽魂之狼数量：',
  cooldownMode: '冷却计算模式：',
  curseOverlaps: '诅咒重叠数：',
  customMods: '自定义词条',
  darkPactSkeletonLife: '骷髅生命：',
  deathmarkDeathmarkActive: '敌人被猎杀信号标记？',
  deliriousPercentage: '谵妄效果：',
  demonFormStacks: '恶魔之焰层数',
  detonateDeadCorpseLife: '敌方尸体生命：',
  doomBlastSource: '厄运冲击触发来源：',
  eldritchEmpowermentSacrifice: '正在献祭？',
  elementalConfluxElement: '元素汇流元素：',
  embraceMadnessActive: '拥抱疯狂生效中？',
  enemyArmour: '敌人基础护甲：',
  enemyBlockChance: '敌人格挡率：',
  enemyChaosDamage: '敌方技能混沌伤害：',
  enemyChaosResist: '敌人混沌抗性：',
  enemyColdDamage: '敌方技能冰霜伤害：',
  enemyColdPen: '敌方技能冰霜穿透：',
  enemyColdResist: '敌人冰霜抗性：',
  enemyConditionHitByColdDamage: '敌人被冰霜伤害击中过？',
  enemyConditionHitByFireDamage: '敌人被火焰伤害击中过？',
  enemyConditionHitByLightningDamage: '敌人被闪电伤害击中过？',
  enemyCritChance: '敌人暴击率：',
  enemyCritDamage: '敌人暴击伤害加成：',
  enemyCriticalWeaknessStacks: '致命弱点层数：',
  enemyDamageRollRange: '敌方技能伤害掷值范围 %：',
  enemyDamageType: '敌人伤害类型：',
  enemyDistance: '与敌人的距离：',
  enemyEvasion: '敌人基础闪避：',
  enemyFireDamage: '敌方技能火焰伤害：',
  enemyFirePen: '敌方技能火焰穿透：',
  enemyFireResist: '敌人火焰抗性：',
  enemyInRFOrScorchingRay: '敌人处于正义之火或灼热光线中：',
  enemyIsBoss: '敌人是 Boss？',
  enemyLevel: '敌人等级：',
  enemyLightningDamage: '敌方技能闪电伤害：',
  enemyLightningPen: '敌方技能闪电穿透：',
  enemyLightningResist: '敌人闪电抗性：',
  enemyMaxResist: '敌人最大抗性恒为 75%',
  enemyMultiplierEnemyPresenceSeconds: '敌人处于你临在范围的时长',
  enemyMultiplierPvpDamage: '自定义 PvP 伤害乘数百分比：',
  enemyPhysicalDamage: '敌方技能物理伤害：',
  enemyPhysicalOverwhelm: '敌方技能物理压制：',
  enemyPhysicalReduction: '敌人物理减伤：',
  enemyRadius: '敌人体型半径：',
  enemySizePreset: '敌人体型预设：',
  enemySpeed: '敌人攻击/施法间隔（毫秒）：',
  eyeOfWinterCold: '冬之眼获得冰霜伤害：',
  eyeOfWinterFire: '冬之眼获得火焰伤害：',
  eyeOfWinterLightning: '冬之眼获得闪电伤害：',
  flameWallAddedDamage: '投射物穿过火墙？',
  flameWallInfused: '闪电灌注？',
  freshMeatBuffs: '鲜肉增益生效中？',
  frostShieldStages: '层数：',
  greaterHarbingerOfTimeSlipstream: '时缝生效中？',
  harbingerOfTimeSlipstream: '时缝生效中？',
  heraldOfAgonyVirulenceStack: '剧毒层数：',
  highestDamageType: '最高伤害类型覆盖：',
  hoaOverkill: '溢出击杀伤害：',
  iceNovaCastOnFrostbolt: '对寒冰弹施放？',
  ignoreItemDisablers: '不禁用物品',
  ignoreJewelLimits: '忽略珠宝数量上限',
  inDemonForm: '处于恶魔形态？',
  incisionConsumedRecently: '最近消耗的切口数量：',
  infusedChannellingInfusion: '灌注生效中？',
  intensifyIntensity: '强度层数：',
  lifeRegenMode: '生命回复计算模式：',
  linkedSourceRate: '直觉联结的来源速率',
  linkedToMinion: '与召唤物联结？',
  manabondMissingUnreservedManaPercentage: '缺失的未保留魔力 %：',
  meatShieldEnemyNearYou: '敌人在你附近？',
  minesPerThrow: '每次投掷的地雷数：',
  minionBuffOnslaught: '你的召唤物拥有猛攻？',
  minionbuffChaoticMight: '你的召唤物拥有混沌之力？',
  minionbuffUnholyMight: '你的召唤物拥有不洁之力？',
  minionsConditionCreatedRecently: '你的召唤物最近被创建？',
  minionsConditionFullEnergyShield: '召唤物总是满能量护盾？',
  minionsConditionFullLife: '你的召唤物总是满血？',
  minionsConditionLeechingEnergyShield: '召唤物在偷取能量护盾？',
  minionsOverrideEnduranceCharges: '耐力球数量（非最大值时）：',
  minionsOverrideFrenzyCharges: '狂怒球数量（非最大值时）：',
  minionsOverridePowerCharges: '暴击球数量（非最大值时）：',
  minionsUseEnduranceCharges: '你的召唤物使用耐力球？',
  minionsUseFrenzyCharges: '你的召唤物使用狂怒球？',
  minionsUsePowerCharges: '你的召唤物使用暴击球？',
  momentumDamage: '技能使用期间移动了 2 米？',
  multiplierAffectedByWarcryBuffDuration: '受战吼增益影响的秒数：',
  multiplierAppliedAilmentsRecently: '最近施加的异常状态数量：',
  multiplierArmourBreak: '护甲破坏值（非最大值时）：',
  multiplierBeenHitRecently: '最近被击中的次数：',
  multiplierBleedsOnEnemy: '敌人身上的流血数量（非平均值时）：',
  multiplierBoltsReloadedPer6Seconds: '过去 6 秒装填的弩箭数',
  multiplierBoltsReloadedPer8Seconds: '过去 8 秒装填的弩箭数',
  multiplierCastLast8Seconds: '最近 8 秒内施放的法术数量？',
  multiplierChannelling: '已引导的秒数：',
  multiplierChilledByYouSeconds: '敌人被冰缓的秒数？',
  multiplierCombo: '连击数：',
  multiplierCorpseConsumedRecently: '最近吞噬的尸体数量：',
  multiplierCorrosionStackCount: '腐蚀层数：',
  multiplierCurrentEnergyShield: '当前能量护盾百分比：',
  multiplierCurrentManaPercentage: '当前魔力 %：',
  multiplierCurseDurationExpiredOnEnemy: '敌人身上诅咒已过期时长：',
  multiplierCurseExpiredOnEnemy: '敌人身上诅咒已过期 %：',
  multiplierDefiance: '反抗值：',
  multiplierDifferentAmmoFired: '过去 10 秒射出的不同弹药种类数',
  multiplierDifferentGrenadeFired: '过去 10 秒射出的不同榴弹种类数',
  multiplierEnduranceChargesLostRecently: '最近失去的耐力球数量：',
  multiplierEnemyAffectedByGraspingVines: '影响敌人的缠身藤蔓数量：',
  multiplierEnsnaredStackCount: '缠困层数：',
  multiplierFaerieFireStackCount: '妖火层数：',
  multiplierFragileRegrowth: '脆弱再生层数：',
  multiplierFreezeShockIgniteOnEnemy: '敌人身上冻结/感电/点燃的数量：',
  multiplierFrozenByYouSeconds: '敌人被冻结的秒数？',
  multiplierHazardsTriggeredRecently: '最近触发的危害物数量：',
  multiplierHexDoom: '咒厄层数：',
  multiplierHitsSuppressedRecently: '最近压制的击中次数：',
  multiplierIgniteAppliedRecently: '最近施加的点燃数量：',
  multiplierIgniteOnEnemy: '敌人身上的点燃数量（非平均值时）：',
  multiplierImpalesOnEnemy: '敌人身上的穿刺数量（非最大值时）：',
  multiplierIncisionStackCount: '切口层数：',
  multiplierKilledRecently: '最近击杀的敌人数量：',
  multiplierLifeSpentPast8s: '过去 8 秒消耗的生命：',
  multiplierLifeSpentRecently: '最近消耗的生命：',
  multiplierLinkedTargets: '联结目标数量：',
  multiplierManaSpentRecently: '最近消耗的魔力：',
  multiplierMineDetonatedRecently: '最近引爆的地雷数量：',
  multiplierMinionsInPresence: '临在范围内的召唤物数量：',
  multiplierMinionsKilledRecently: '召唤物最近击杀的敌人数量：',
  multiplierNearbyAlly: '附近盟友数量：',
  multiplierNearbyCorpse: '附近尸体数量：',
  multiplierNearbyEnemies: '附近敌人数量：',
  multiplierNearbyRareOrUniqueEnemies: '附近稀有或传奇敌人数量：',
  multiplierNonInstantSpellCastRecently: '最近施放的非瞬发法术数量：',
  multiplierPoisonAppliedRecently: '最近施加的中毒数量：',
  multiplierPoisonOnEnemy: '敌人身上的中毒数量（非平均值时）：',
  multiplierPoisonOnSelf: '你身上的中毒数量：',
  multiplierPvpDamage: '自定义 PvP 伤害乘数百分比：',
  multiplierPvpTvalueOverride: 'PvP T 值覆盖（毫秒）：',
  multiplierRage: '怒火：',
  multiplierRampage: '暴走击杀数：',
  multiplierRuptureStacks: '破裂层数？',
  multiplierShockedEnemyKilledRecently: '最近击杀的感电敌人数量：',
  multiplierShockedNonShockedEnemyRecently: '最近感电的非感电敌人数量：',
  multiplierSkillUsedRecently: '最近使用的技能数量：',
  multiplierSoulEater: '噬魂层数：',
  multiplierStunnedRecently: '最近被晕眩的次数：',
  multiplierSummonedMinion: '已召唤召唤物数量（非最大值时）：',
  multiplierTailwind: '提速尾流层数：',
  multiplierTotemsKilledRecently: '图腾最近击杀的敌人数量：',
  multiplierTrapTriggeredRecently: '最近触发的陷阱数量：',
  multiplierWarcryPower: '战吼威力值：',
  multiplierWarcryUsedRecently: '最近使用的战吼数量：',
  multiplierWitheredStackCount: '凋落层数：',
  multiplierWitheredStackCountSelf: '你身上的凋落层数：',
  multiplierWoCExpiredDuration: '定罪波已过期时长 %：',
  nearbyBleedingEnemies: '附近流血敌人数量：',
  overrideBlitzCharges: '闪打球数量（非最大值时）：',
  overrideBloodCharges: '鲜血球数量（非最大值时）：',
  overrideBuffBlinded: '致盲效果（非最大值时）：',
  overrideBuffElusive: '灵巧效果（非平均值时）：',
  overrideChallengerCharges: '挑战者球数量（非最大值时）：',
  overrideCrabBarriers: '灵蟹屏障数量（非最大值时）：',
  overrideCruelty: '伤害 %（非最大值时）：',
  overrideEnduranceCharges: '耐力球数量（非最大值时）：',
  overrideFortification: '巩固层数（非最大值时）：',
  overrideFrenzyCharges: '狂怒球数量（非最大值时）：',
  overrideGhostShrouds: '鬼影缠身数量（非最大值时）：',
  overrideInspirationCharges: '激励球数量（非最大值时）：',
  overridePowerCharges: '暴击球数量（非最大值时）：',
  overrideSiphoningCharges: '虹吸球数量（非最大值时）：',
  overrideSpiritCharges: '精魂球数量：',
  parryActive: '敌人有招架破绽减益',
  perforateSpikeOverlap: '重叠的尖刺数量：',
  physMode: '随机元素模式：',
  physicalAegisDepleted: '物理神盾已耗尽？',
  plagueBearerState: '状态：',
  presetBossSkills: 'Boss 技能预设',
  prideEffect: '傲慢光环效果：',
  purpleFlameStacks: '收集的紫焰数量：',
  'questAct 1ClearfellBeira': '第一章：净空林地',
  'questAct 1FreythornKing In The Mists': '第一章：弗雷索恩',
  'questAct 1Ogham ManorCandlemass': '第一章：欧甘庄园',
  'questAct 2Spires of DesharSisters of Garukhan Shrine': '第二章：德沙尔尖塔',
  'questAct 2Valley of the TitansMedallion': '第二章：泰坦之谷',
  'questAct 3Azak BogIgnagduk': '第三章：阿扎克沼泽',
  "questAct 3Jiquani's MachinariumBlackjaw": '第三章：基卡尼机关殿',
  'questAct 3Venom CryptsVenom Draught': '第三章：毒液地窖',
  'questAct 4Abandoned PrisonGoddess of Justice': '第四章：废弃监狱',
  'questAct 4Eye of HinekoraSilent Hall': '第四章：希内蔻拉之眼',
  'questAct 4Eye of HinekoraTribal Medicine': '第四章：希内蔻拉之眼',
  "questAct 4Halls Of The DeadNgamahu's Test": '第四章：亡者之殿',
  "questAct 4Halls Of The DeadTasalio's Test": '第四章：亡者之殿',
  "questAct 4Halls Of The DeadTawhoa's Test": '第四章：亡者之殿',
  'questInterlude 2Khari CrossingMolten Shrine': '幕间 2：卡里渡口',
  'questInterlude 2QimahSeven Pillars': '幕间 2：奇玛',
  'questInterlude 3Kriar VillageLythara': '幕间 3：克里亚村',
  raiseSpectreBladeVortexBladeCount: '飞刃风暴刀刃数量：',
  raiseSpectreEnableBuffs: '启用增益：',
  raiseSpectreEnableCurses: '启用诅咒：',
  raiseSpectreEnableSanguimancerDemonLowLife: '血术恶魔不处于低血：',
  raiseSpectreEnableSlashingHorrorEnrage: '禁用斩击惊魂的激怒：',
  raiseSpectreEnableSummonedUrsaRallyingCry: '启用召唤熊怪的集结战吼：',
  raiseSpectreKaomFireBeamTotemStage: '灼热光线图腾层数：',
  raiseSpidersSpiderCount: '蜘蛛数量：',
  repeatMode: '重复模式：',
  reservedDarkness: '保留的黑暗值：',
  resistancePenalty: '元素抗性惩罚：',
  resourceGainMode: '资源获取计算模式：',
  risingTempestCold: '最近使用过冰霜技能：',
  risingTempestFire: '最近使用过火焰技能：',
  risingTempestLightning: '最近使用过闪电技能：',
  ruthlessSupportMode: '无情辅助模式：',
  sacrificedRageCount: '献祭的怒火数量（非最大值时）：',
  scavengedPlatingStacks: '拾荒护甲层数：',
  shardsConsumed: '已消耗的钢铁碎片：',
  sigilOfPowerStages: '层数：',
  siphoningTrapAffectedEnemies: '受影响的敌人数量：',
  skillChainCount: '技能已连锁次数：',
  skillForkCount: '技能已分裂次数：',
  skillPierceCount: '技能已穿透次数：',
  steelWards: '钢铁结界数：',
  stoicismSeconds: '累积坚忍的秒数：',
  stoneGolemEqualsCarrionGolem: '石魔像数 = 腐肉魔像数：',
  stormRainActiveArrows: '激活的箭矢数量：',
  stormRainBeamOverlap: '重叠的光束数量：',
  summonCompanionEnableBuffs: '启用增益：',
  summonCompanionEnableCurses: '启用诅咒：',
  summonElementalRelicEnableAngerAura: '启用愤怒光环：',
  summonElementalRelicEnableHatredAura: '启用憎恨光环：',
  summonElementalRelicEnableWrathAura: '启用雷霆光环：',
  summonHolyRelicEnableHolyRelicBoon: '启用神圣遗物的恩赐光环：',
  summonLightningGolemEnableWrath: '启用雷霆光环：',
  summonReaperConsumeRecently: '收割者最近吞噬过？',
  targetBrandedEnemy: '技能正瞄准被烙印的敌人',
  tornadoShotSecondaryHitChance: '第二支投射物命中几率 %：',
  touchedDebuffsCount: '光辉疯狂层数',
  toxicRainPodOverlap: '重叠的毒荚数量：',
  trapsPerThrow: '每次投掷的陷阱数：',
  traumaStacks: '创伤层数：',
  twisterCold: '旋风获得冰霜元素：',
  twisterFire: '旋风获得火焰元素：',
  twisterLightning: '旋风获得闪电元素：',
  unwillingOfferingPower: '被淘汰敌人的威力？',
  useBlitzCharges: '使用闪打球？',
  useChallengerCharges: '使用挑战者球？',
  useEnduranceCharges: '使用耐力球？',
  useFrenzyCharges: '使用狂怒球？',
  useGhostShrouds: '使用鬼影缠身？',
  usePowerCharges: '使用暴击球？',
  useSiphoningCharges: '使用虹吸球？',
  voltaxicBurstSpellsQueued: '当前排队等待的施放数量：',
  vortexCastOnFrostbolt: '对寒冰弹施放？',
  waitForMaxSeals: '等待最大封印数？',
  warcryMode: '战吼强化计算模式：',
  whirlwindBuffCold: '回旋之风获得冰霜元素：',
  whirlwindBuffFire: '回旋之风获得火焰元素：',
  whirlwindBuffLightning: '回旋之风获得闪电元素：',
  whirlwindStages: '回旋之风层数：',
  windDancerStacks: '风舞者层数：',
};

/** 常见 list 选项词（计算口径类）；词条文本型选项走 translateLines 反查。 */
export const LIST_OPTION_ZH: Record<string, string> = {
  Average: '平均值',
  Minimum: '最小值',
  Maximum: '最大值',
  Base: '基础',
  None: '无',
  Fire: '火焰',
  Cold: '冰霜',
  Lightning: '闪电',
  Chaos: '混沌',
  Physical: '物理',
  Random: '随机',
  Melee: '近战',
  Projectile: '投射物',
  Spell: '法术',
  'Area of Effect': '范围效果',
  Unlucky: '不幸',
  Lucky: '幸运',
  Small: '小型',
  Medium: '中型',
  Large: '大型',
  Boss: 'Boss',
  Blood: '血姿态',
  Sand: '沙姿态',
  'Act 1 (0%)': '第一章（0%）',
  'Act 2 (-10%)': '第二章（-10%）',
  'Act 3 (-20%)': '第三章（-20%）',
  'Act 4 (-30%)': '第四章（-30%）',
  'Act 5 (-40%)': '第五章（-40%)',
  'Act 6 (-50%)': '第六章（-50%）',
  'Endgame (-60%)': '终局（-60%）',
};
