import type { Lang } from './i18n';

const text = {
  title: ['Build references', '流派參考', '流派参考'],
  hint: ['Find a related build, understand the differences, then verify an upgrade on your character.', '尋找近似構築、理解差異，再驗證對自己角色的提升。', '寻找近似构筑、理解差异，再验证对自己角色的提升。'],
  identity: ['Your current build', '目前構築', '当前构筑'],
  noSkill: ['Select a main skill to get meaningful matches.', '先選擇主技能，以取得有意義的配對。', '先选择主技能，以获得有意义的匹配。'],
  next: ['What to improve next', '下一步如何增強', '下一步如何增强'],
  gaps: ['Check elemental resistance gaps', '檢查元素抗性缺口', '检查元素抗性缺口'],
  target: ['Target', '目標', '目标'],
  gapHint: ['Start with these gaps when comparing equipment. The target follows your upgrade settings.', '比較裝備時先留意這些缺口，目標沿用提升頁設定。', '比较装备时先留意这些缺口，目标沿用提升页设置。'],
  skills: ['Skills & support gems', '技能與輔助寶石', '技能与辅助宝石'],
  skillHint: ['Compare the selected skill’s levels, quality and supports. Calculate compatible combinations before changing them.', '對照主技能的等級、品質與輔助；先重算相容組合，再決定調整。', '对照主技能的等级、品质与辅助；先重算兼容组合，再决定调整。'],
  gear: ['Equipment', '裝備', '装备'],
  evaluateItem: ['Evaluate on my character', '以我的角色試算', '以我的角色试算'],
  gearHint: ['Compare complete items and socketing. A shared unique is a similarity signal, not proof that you need it.', '比較完整裝備與插槽效果；相同傳奇是配對線索，不代表必備。', '比较完整装备与插槽效果；相同传奇是匹配线索，不代表必备。'],
  tree: ['Key passives', '關鍵天賦', '关键天赋'],
  treeHint: ['Review effects and trade-offs, then plan connected paths with travel and respec costs.', '先看效果與代價，再規劃包含過路點與洗點成本的連通路徑。', '先看效果与代价，再规划包含过路点与洗点成本的连通路径。'],
  calculate: ['Open upgrade planner', '開啟提升規劃', '打开提升规划'],
  configure: ['Review combat conditions', '核對戰鬥條件', '核对战斗条件'],
  partial: ['Some effects or items are not calculated. Resolve the coverage gaps before trusting upgrade percentages.', '有部分效果或裝備未納入計算，判斷提升百分比前請先核對。', '有部分效果或装备未纳入计算，判断提升百分比前请先核对。'],
  live: ['Find builds on poe.ninja', '在 poe.ninja 尋找構築', '在 poe.ninja 寻找构筑'],
  league: ['League', '賽季', '赛季'],
  otherLeague: ['Another league…', '其他賽季…', '其他赛季…'],
  leagueCode: ['League code after /poe2/builds/', '/poe2/builds/ 後的賽季代碼', '/poe2/builds/ 后的赛季代码'],
  leagueHint: ['Choose the same league as your character. Links search poe.ninja using the selected main skill and class.', '選擇與角色相同的賽季，依目前主技能與職業到 poe.ninja 搜尋。', '选择与角色相同的赛季，按当前主技能与职业到 poe.ninja 搜索。'],
  sameClass: ['Same ascendancy / class', '同升華／職業', '同升华／职业'],
  searchLive: ['Search current skill', '搜尋目前技能', '搜索当前技能'],
  leagues: ['Choose a league on poe.ninja', '查看 poe.ninja 賽季', '查看 poe.ninja 赛季'],
  samples: ['Related reference builds', '近似參考構築', '近似参考构筑'],
  history: ['Historical samples, not live ladder rankings. Source league, patch and date are shown on each build; results do not establish the current meta.', '歷史樣本，非即時天梯。每份標示賽季、版本與日期，不代表目前主流強度。', '历史样本，非实时天梯。每份标示赛季、版本与日期，不代表当前主流强度。'],
  search: ['Filter by skill, class or unique', '依技能、職業或傳奇篩選', '按技能、职业或传奇筛选'],
  exact: ['Same main skill only', '只看相同主技能', '只看相同主技能'],
  empty: ['No matching samples. Relax the filters or find a reference on poe.ninja and paste its PoB2 code below.', '沒有符合的樣本。可放寬篩選，或從 poe.ninja 取得參考 PoB2 代碼貼到下方。', '没有符合的样本。可放宽筛选，或从 poe.ninja 获取参考 PoB2 代码粘贴到下方。'],
  loading: ['Loading reference builds…', '載入參考構築中…', '正在加载参考构筑…'],
  failed: ['Reference samples could not be loaded. You can still paste a reference code.', '參考樣本載入失敗，仍可貼上參考代碼。', '参考样本加载失败，仍可粘贴参考码。'],
  retry: ['Retry', '重試', '重试'],
  score: ['Match points', '配對分', '匹配分'],
  formula: ['Main skill 55; ascendancy 20 (or class 10); support overlap 15; unique overlap 10. Missing signals earn no points. This is not an upgrade percentage.', '主技能 55；升華 20（或職業 10）；輔助重合 15；傳奇重合 10。缺少資料不加分，分數不是提升百分比。', '主技能 55；升华 20（或职业 10）；辅助重合 15；传奇重合 10。缺少数据不加分，分数不是提升百分比。'],
  sameSkill: ['Same main skill', '相同主技能', '相同主技能'],
  otherSkill: ['Different main skill', '不同主技能', '不同主技能'],
  ascendancy: ['Same ascendancy', '相同升華', '相同升华'],
  baseClass: ['Same class', '相同職業', '相同职业'],
  supports: ['Support overlap', '輔助重合', '辅助重合'],
  uniques: ['Unique overlap', '傳奇重合', '传奇重合'],
  source: ['View source', '查看來源', '查看来源'],
  details: ['Compare details', '對照細節', '对照细节'],
  pasteTitle: ['Bring another reference', '加入另一份參考', '加入另一份参考'],
  pasteHint: ['Copy a PoB2 export code from a poe.ninja character. This opens a comparison without replacing your build. Pasted references stay in this view only.', '複製 poe.ninja 角色的 PoB2 匯出碼，可直接比較，不替換目前構築。貼上的參考僅保留在此頁。', '复制 poe.ninja 角色的 PoB2 导出码，可直接比较，不替换当前构筑。粘贴的参考仅保留在此页。'],
  paste: ['Reference PoB2 code', '參考 PoB2 代碼', '参考 PoB2 代码'],
  compare: ['Open reference', '開啟參考', '打开参考'],
  pasted: ['Pasted reference · league and date unverified', '貼上參考 · 賽季與日期未確認', '粘贴参考 · 赛季与日期未确认'],
  current: ['Current', '目前', '当前'],
  reference: ['Reference', '參考', '参考'],
  absent: ['Not present', '未配置', '未配置'],
  gem: ['Gem', '寶石', '宝石'],
  level: ['Level', '等級', '等级'],
  quality: ['Quality', '品質', '品质'],
  mainOnly: ['Selected main groups. Supports on a different main skill are not directly transferable.', '對照所選主技能組。不同主技能的輔助不可直接照搬。', '对照所选主技能组。不同主技能的辅助不可直接照搬。'],
  slot: ['Position', '部位', '部位'],
  text: ['Full item text', '完整物品文字', '完整物品文本'],
  differences: ['Different setups require coordinated changes. These differences are observations; the planners calculate candidate gains using your current build.', '不同流派可能需要配套調整。這裡列出配置差異，候選收益由規劃器以目前構築重算。', '不同流派可能需要配套调整。这里列出配置差异，候选收益由规划器以当前构筑重算。'],
  passiveVersion: ['Passive IDs are resolved against the installed game data. Historical names and effects may have changed; verify the source before planning a respec.', '天賦 ID 以目前遊戲資料解讀；歷史名稱與效果可能變動，洗點前請核對來源。', '天赋 ID 以当前游戏数据解读；历史名称与效果可能变动，洗点前请核对来源。'],
  noPassives: ['No resolved keystones or notables.', '沒有可辨識的核心或重要天賦。', '没有可识别的核心或重要天赋。'],
  notes: ['Reference notes', '參考筆記', '参考笔记'],
  notesHint: ['Author text is reference material; it is not a verified upgrade recommendation.', '作者文字僅供參考，不代表已驗證的提升建議。', '作者文字仅供参考，不代表已验证的提升建议。'],
  noNotes: ['No notes in this reference.', '此參考沒有筆記。', '此参考没有笔记。'],
  notRelated: ['No shared main skill, class or unique found. Browse these as alternatives, not close matches.', '未找到相同主技能、職業或傳奇。以下供探索其他流派，不屬於近似配對。', '未找到相同主技能、职业或传奇。以下供探索其他流派，不属于近似匹配。'],
} satisfies Record<string, [string, string, string]>;
export function guidanceT(lang: Lang, key: keyof typeof text): string {
  return text[key][lang === 'en-US' ? 0 : lang === 'zh-TW' ? 1 : 2];
}
