import type { Lang } from './i18n';

const labels = {
  equipment: ['Equipment upgrades', '裝備提升', '装备提升'],
  equipmentHint: ['Rank positions and compare complete replacement items.', '比較全身提升空間與整件換裝收益。', '比较全身提升空间与整件换装收益。'],
  supports: ['Skill and support setup', '技能與輔助搭配', '技能与辅助搭配'],
  supportsHint: ['Automatically evaluate eligible supports and their combinations.', '自動篩選可用輔助，重算完整組合。', '自动筛选可用辅助，重算完整组合。'],
  tree: ['Passive point planning', '天賦點規劃', '天赋点规划'],
  treeHint: ['Compare connected paths, travel cost and respec options.', '比較連通路徑、過路點成本與洗點方案。', '比较连通路径、过路点成本与洗点方案。'],
  open: ['Open planner', '開始規劃', '开始规划'],
  currentScore: ['Current item · market Sum', '目前裝備 · 市集 Sum', '当前装备 · 市集 Sum'],
  complete: ['Comparable stat score', '同口徑詞條分數', '同口径词条分数'],
  partial: ['Partial score · no minimum filter', '部分詞條可比 · 不設最低分', '部分词条可比 · 不设最低分'],
  noScore: ['No comparable item score', '尚無可比裝備分數', '尚无可比装备分数'],
  scoreHint: ['Sum ranks weighted affixes, not DPS. Base stats, local modifiers and interactions can reverse market rankings; paste the complete item into the comparison above.', 'Sum 是詞條加權分，不是 DPS。基底、局部詞條與交互作用可能改變排名；請把完整物品貼到上方比較。', 'Sum 是词条加权分，不是 DPS。基底、局部词条与交互作用可能改变排名；请把完整物品粘贴到上方比较。'],
  scoreDetails: ['Current item score breakdown', '目前裝備評分明細', '当前装备评分明细'],
  marginal: ['Marginal estimate', '邊際估算', '边际估算'],
  check: ['Paste a market item and compare', '貼上市集物品，直接比較', '粘贴市集物品，直接比较'],
  checkHint: ['Use Copy Item on the official market, then paste the complete text here. We identify its base and compare every compatible equipped position, including both rings.', '在官方市集複製完整物品文本並貼到這裡，自動辨識基底、比較所有可替換的已裝備位置，包括兩枚戒指。', '在官方市集复制完整物品文本并粘贴到这里，自动识别基底、比较所有可替换的已装备位置，包括两枚戒指。'],
  pasteEyebrow: ['Found something in the market?', '看到心儀的市集物品？', '看到心仪的市集物品？'],
  localComparison: ['Local calculation', '本地計算', '本地计算'],
  comparisonGoal: ['Comparison goal', '比較目標', '比较目标'],
  pastePlaceholder: ['Paste the full copied item, including Rarity, its base and modifiers…', '貼上包含稀有度、基底與詞綴的完整物品文本…', '粘贴包含稀有度、基底与词缀的完整物品文本…'],
  autoPositions: ['Pasting starts comparison automatically. No position selection needed.', '貼上後自動比較，無需先選位置。', '粘贴后自动比较，无需先选位置。'],
  comparingPositions: ['Comparing positions…', '正在比較各位置…', '正在比较各位置…'],
  cancelCompare: ['Cancel comparison', '取消比較', '取消比较'],
  parsedItem: ['Parsed item', '已辨識物品', '已识别物品'],
  parsedAffixes: ['Item modifiers', '物品詞綴', '物品词缀'],
  requiredLevel: ['Required level', '需求等級', '需求等级'],
  noAffixes: ['No item modifiers in this text.', '文本中沒有物品詞綴。', '文本中没有物品词缀。'],
  requirementsNote: ['Position and level are checked. Attribute requirements and special equip rules still need to be verified before buying.', '已檢查位置與等級；購買前仍需核對屬性需求與特殊裝備規則。', '已检查位置与等级；购买前仍需核对属性需求与特殊装备规则。'],
  chooseReplacement: ['Replacement position', '替換位置', '替换位置'],
  recommendedPosition: ['Best for your goal', '目前目標優先', '当前目标优先'],
  jewelPosition: ['Jewel socket', '珠寶插槽', '珠宝插槽'],
  noCompatibleSlot: ['No compatible equipped position or allocated jewel socket was found. Configure the intended equipment position first.', '目前沒有可替換的已裝備位置或已分配珠寶插槽，請先配置對應裝備位置。', '当前没有可替换的已装备位置或已分配珠宝插槽，请先配置对应装备位置。'],
  partialReplacement: ['Partial calculation · some effects are not modeled', '部分計算 · 有效果尚未建模', '部分计算 · 有效果尚未建模'],
  applyHint: ['Your build changes only when you apply.', '按下套用後才會變更構築。', '点击应用后才会更改构筑。'],
  itemText: ['Complete item text', '完整物品文本', '完整物品文本'],
  compare: ['Calculate replacement', '重算換裝', '重算换装'],
  apply: ['Apply to build', '套用到構築', '应用到构筑'],
  before: ['Current', '目前', '当前'],
  after: ['Replacement', '換裝後', '换装后'],
  change: ['Change', '變化', '变化'],
  better: ['Improves the selected goal', '符合目前目標的提升', '符合当前目标的提升'],
  worse: ['Does not improve the selected goal', '未改善目前目標', '未改善当前目标'],
  dpsDrop: ['DPS decreases after this replacement', '此方案換裝後 DPS 下降', '此方案换装后 DPS 下降'],
  constraintFail: ['Does not meet your survival / stat floor', '未滿足生存／屬性底線', '未满足生存／属性底线'],
  incomplete: ['Some effects could not be calculated. Treat these values as incomplete.', '部分效果未能計算，以上數值並不完整。', '部分效果未能计算，以上数值并不完整。'],
  invalidItem: ['Copy the full item, including its rarity and base. English and Chinese clipboard headers are supported.', '請複製包含稀有度與基底的完整物品；支援中英文物品標頭。', '请复制包含稀有度与基底的完整物品；支持中英文物品头部。'],
  skippedUnmodeled: ['Reference items with newly unmodeled effects were excluded from recommendations.', '含新增未建模效果的參考物品已排除推薦。', '含新增未建模效果的参考物品已排除推荐。'],
  marketConstraints: ['Survival floors and resistance priority apply to local calculations. The official market Sum does not enforce them; check the complete item before buying.', '生存底線與抗性優先用於本地計算，官方市集 Sum 不保證滿足。購買前請核對整件物品。', '生存底线与抗性优先用于本地计算，官方市集 Sum 不保证满足。购买前请核对整件物品。'],
  unknownBase: ['Cannot verify the item base. Copy the complete item with its base name.', '無法確認基底，請複製包含基底名稱的完整物品。', '无法确认基底，请复制包含基底名称的完整物品。'],
  wrongSlot: ['This item does not fit the selected position.', '此物品不適用於目前位置。', '此物品不适用于当前位置。'],
  weaponType: ['This weapon family requires a coordinated skill/offhand change. Configure it on Equipment first.', '變更武器類型需要同時調整技能與副手，請先到裝備頁配置。', '变更武器类型需要同时调整技能与副手，请先到装备页配置。'],
  itemLevel: ['Required level exceeds your character level.', '需求等級高於角色等級。', '需求等级高于角色等级。'],
  unidentified: ['Identify the item before comparing its effects.', '請先鑑定物品再比較效果。', '请先鉴定物品再比较效果。'],
  advancedGoal: ['Stat constraints', '屬性約束', '属性约束'],
  adjustment: ['Skill adjustment · no market purchase', '技能調整 · 無需市集購買', '技能调整 · 无需市集购买'],
  lineage: ['Lineage support', '血脈輔助', '血脉辅助'],
  autoSupports: ['Find all usable supports', '自動尋找可用輔助', '自动寻找可用辅助'],
  sharedGoal: ['Your goal follows equipment, skills and passives. Each suggestion uses the current main skill and weapon set.', '裝備、技能與天賦共用目標；每項建議均使用目前主技能和武器組。', '装备、技能与天赋共用目标；每项建议均使用当前主技能和武器组。'],
} as const;

export function upgradeT(lang: Lang, key: keyof typeof labels): string {
  return labels[key][lang === 'en-US' ? 0 : lang === 'zh-TW' ? 1 : 2];
}
