import type { Lang } from './i18n';
const text = {
  'en-US': {
    libraryTitle: "My builds",
    libraryHint: "Each build is saved independently on this browser.",
    currentBuild: "Current build",
    stagesTitle: "Stages in this build",
    stagesHint: "Each stage keeps its own tree, gear, skills, configuration and notes. Copy a stage to plan your next upgrade.",
    stageScope: "Editing this stage",
    importedLoadouts: "Imported PoB loadouts",
    importedLoadoutsHint: "These are sets from the imported PoB file. Switching reloads the source into the current stage and replaces its edits.",
    importDestination: "Import into",
    importNew: "New build",
    importCurrent: "Replace current stage",
    replaceConfirm: "Replace only the current stage? Other stages and builds stay saved.",
    importFileHint: "Shared build files add a build; workspace backups restore the whole library.",
    exportTitle: "Share & backup",
    currentStageShare: "PoB code · current stage",
    backupHint: "Includes all local builds, stages and unapplied drafts.",

    builds: 'Build', stages: 'Stage', initialBuild: 'My build', initialStage: 'Current', manage: 'Manage builds',
    title: 'Builds & stages', hint: 'Keep separate builds for different skills. Copy a stage to plan leveling, progression or endgame with its own tree, gear and notes.',
    newBuild: 'New build', copyStage: 'Copy current stage', renameBuild: 'Rename build', renameStage: 'Rename stage',
    name: 'Name', save: 'Save', cancel: 'Cancel', saved: 'Saved locally', failed: 'Browser save failed. Download a backup before closing this page.',
    share: 'Share this build · all stages', backup: 'Back up all builds', shareHint: 'The build file includes every stage, passive allocation and note. Import it on Build to add it to your library. PoB codes include this stage and its imported PoB loadouts, but exclude other local stages.',
    backupConfirm: 'Restore this backup? It will replace all locally saved builds. Download your current backup first.',
    importHint: 'Import creates a new build by default. Choose replacement only to update the current stage.',
    start: 'Starter', progress: 'Progression', endgame: 'Endgame',
  },
  'zh-CN': {
    libraryTitle: "我的 BD",
    libraryHint: "每份 BD 独立保存在当前浏览器中。",
    currentBuild: "当前 BD",
    stagesTitle: "此 BD 的阶段",
    stagesHint: "每个阶段保存完整的天赋、装备、技能、配置和笔记。复制阶段可规划下一步提升。",
    stageScope: "正在编辑此阶段",
    importedLoadouts: "导入的 PoB 配装",
    importedLoadoutsHint: "这些是导入文件中的配置组合。切换会重新读取原文件，替换当前阶段的编辑内容。",
    importDestination: "导入到",
    importNew: "新 BD",
    importCurrent: "替换当前阶段",
    replaceConfirm: "替换当前阶段的全部内容？其他阶段和 BD 会保留。",
    importFileHint: "BD 分享文件会新增 BD；完整备份会恢复整个 BD 库。",
    exportTitle: "分享与备份",
    currentStageShare: "PoB 分享码 · 当前阶段",
    backupHint: "包含本机全部 BD、阶段及尚未应用的草稿。",

    builds: 'BD', stages: '阶段', initialBuild: '我的 BD', initialStage: '当前阶段', manage: '管理 BD',
    title: '我的 BD 与阶段', hint: '不同技能玩法独立保存 BD，复制阶段即可规划开荒、过渡与毕业。每个阶段保留自己的天赋、装备、技能和备注。',
    newBuild: '新建 BD', copyStage: '复制当前阶段', renameBuild: '重命名 BD', renameStage: '重命名阶段',
    name: '名称', save: '保存', cancel: '取消', saved: '已保存到本机', failed: '浏览器保存失败，请在关闭页面前下载备份。',
    share: '分享此 BD · 全部阶段', backup: '备份全部 BD', shareHint: 'BD 文件包含所有阶段、加点与备注，可在构筑页导入并加入自己的 BD。PoB 分享码包含当前阶段及导入的 PoB 配装，不包含其他本地阶段。',
    backupConfirm: '恢复此备份会替换本机全部 BD，请先下载当前备份。是否继续？',
    importHint: '导入默认新增 BD。仅在需要更新当前阶段时选择替换。',
    start: '开荒', progress: '过渡', endgame: '毕业',
  },
  'zh-TW': {
    libraryTitle: "我的 BD",
    libraryHint: "每份 BD 獨立儲存在目前瀏覽器中。",
    currentBuild: "目前 BD",
    stagesTitle: "此 BD 的階段",
    stagesHint: "每個階段儲存完整的天賦、裝備、技能、配置和筆記。複製階段可規劃下一步提升。",
    stageScope: "正在編輯此階段",
    importedLoadouts: "匯入的 PoB 配裝",
    importedLoadoutsHint: "這些是匯入檔案中的配置組合。切換會重新讀取原檔案，取代目前階段的編輯內容。",
    importDestination: "匯入至",
    importNew: "新 BD",
    importCurrent: "取代目前階段",
    replaceConfirm: "取代目前階段的全部內容？其他階段和 BD 會保留。",
    importFileHint: "BD 分享檔案會新增 BD；完整備份會還原整個 BD 庫。",
    exportTitle: "分享與備份",
    currentStageShare: "PoB 分享碼 · 目前階段",
    backupHint: "包含本機全部 BD、階段及尚未套用的草稿。",

    builds: 'BD', stages: '階段', initialBuild: '我的 BD', initialStage: '目前階段', manage: '管理 BD',
    title: '我的 BD 與階段', hint: '不同技能玩法獨立儲存 BD，複製階段即可規劃開荒、過渡與畢業。每個階段保留自己的天賦、裝備、技能和備註。',
    newBuild: '新增 BD', copyStage: '複製目前階段', renameBuild: '重新命名 BD', renameStage: '重新命名階段',
    name: '名稱', save: '儲存', cancel: '取消', saved: '已儲存至本機', failed: '瀏覽器儲存失敗，請在關閉頁面前下載備份。',
    share: '分享此 BD · 全部階段', backup: '備份全部 BD', shareHint: 'BD 檔案包含所有階段、加點與備註，可在構築頁匯入並加入自己的 BD。PoB 分享碼包含目前階段及匯入的 PoB 配裝，不包含其他本機階段。',
    backupConfirm: '還原此備份會取代本機全部 BD，請先下載目前備份。是否繼續？',
    importHint: '匯入預設新增 BD。僅在需要更新目前階段時選擇取代。',
    start: '開荒', progress: '過渡', endgame: '畢業',
  },
};
export const workspaceText = (lang: Lang) => text[lang];
