//! Schema for the adapted, stored game-data catalog.
//!
//! This is PoBR's **own minimal JSON schema**, generated by
//! `pobr-data-adapter` from GGG's raw `.dat` export (pathofexile-dat
//! output) by resolving foreign keys and denormalizing, landing in the
//! repo under `data/<poe_version>/` (a three-layer layout: `base/` fully
//! auto-regenerated, `overlay/` vendor-extracted, `generated/`
//! deterministic cache — see P1). Loaded at runtime via serde by the
//! loader (`pobr-gamedata`).
//!
//! Design goals: decoupled from GGG's raw column names / PoB's generated
//! Lua; keeps only the fields calc/display need; stable string IDs;
//! pin-able versions, diff-friendly (arrays sorted by id).
//!
//! Modules are split by data-domain cohesion; every type is fully
//! re-exported via `pub use` here, so external code always references them
//! as `pobr_data::catalog::X` (the split doesn't break existing paths).

pub mod items;
pub mod manifest;
pub mod mods;
pub mod skills;
pub mod tree;

// Empty shells for the nine-table schema (pre-created to avoid parallel-work conflicts; W2 fills in the types)
pub mod base_player_mods;
pub mod character_constants;
pub mod enemy_presets;
pub mod game_constants;
pub mod jewel_radii;
pub mod monster_scaling;
pub mod non_damaging_ailments;
pub mod unarmed_data;
pub mod weapon_types;

// The injection pipeline: the runtime constants bundle calc consumes
pub mod runtime;

// Small lookup-table overlay schemas (the rounding-precision exception table + the local-mod whitelist)
pub mod high_precision_mods;
pub mod local_mods;

// Per-skill override-value overlay schema (vendor Lua extraction)
pub mod skill_overrides;

// SkillStatMap overlay schema (vendor Lua extraction, skill_stat_map/v1)
pub mod stat_map;

//  StatDescriptions overlay schema (the second stat_id → canonical-text channel)
pub mod stat_descriptions;
// Phase 7.1: mod-line input translation templates (i18n/<lang>/stat_lines.json)
pub mod i18n_stat_lines;
pub use i18n_stat_lines::StatLineTemplate;
//  StatId→Modifier mapping table (stat_descriptions baked by the engine's parser)
pub mod stat_id_map;

// Base item override-value overlay schema (extracted from vendor Data/Bases: block/spirit)
pub mod base_item_overrides;

pub use base_item_overrides::{BaseItemOverrideEntry, BaseItemOverridesDef};

//  The restricted-DSL single-source schema + config options catalog + built-in buff definitions
pub mod buffs;
pub mod config_def;
pub mod value_expr;

// M6-C: curse priority data table overlay schema (vendor-extracted, curse_priority/v1)
pub mod curse_priority;

// Data prerequisites
pub mod actors; // M5a: minions / spectres / granted_effect_minions (vendor-extracted)
pub mod item_overlay; // M5c: mod_scalability / catalysts / runes / uniques (vendor-extracted)
pub mod parser_rules; // M5b: special_mods templates (hand-curated) + M6: the ModParser rule six-table set (mod_parser_rules/v1)
pub mod triggers; // M5a-D2: mirage_configs (generated embedded in the tool); M4-T5 extends trigger_configs in the same file
pub mod vendor_name_aliases; // M6.3: the vendor→PoBR ModName alias table (a switchover-prerequisite data asset, zero consumers)

pub use actors::{
    GrantedEffectMinionDef, GrantedEffectMinionsDef, LuaValueDef, MinionEntryDef, MinionModDef,
    MinionsDef,
};
pub use item_overlay::{
    CatalystDef, CatalystsDef, ModScalabilityDef, ModScalabilityEntryDef, ModScalabilitySlotDef,
    RuneDef, RuneSlotDef, RunesDef, UniqueDef, UniquesDef,
};
pub use items::{ArmourBaseStats, BaseItemDef, WeaponBaseStats};
pub use manifest::{CATALOG_SCHEMA_VERSION, DataManifest, DomainSections};
pub use mods::{ModDef, ModStat, SpawnWeight, StatDef};
pub use parser_rules::{
    FlagPhraseDef, FlagTypeDef, FlagTypeModDef, FormDef, MOD_PARSER_RULES_SCHEMA,
    ModParserRulesDoc, ModTemplateDef, NameMapDef, PhraseNamesDef, PhraseValueDef, PreFlagDef,
    RuleEffectsDef, SpecialModsDef, SpecialTemplateDef, TagPhraseDef, TagTemplate, TemplateNameDef,
    TemplateScalarDef, TemplateTagDef, TemplateValueDef, ValueExprDef, ValueOpDef,
};
pub use runtime::RuntimeConstants;
pub use skills::{
    CostTypeDef, DotFlags, GemEffectDef, GemEffectsDef, GemQualityStatDef, GemQualityStatsDef,
    GrantedEffectDef, QualityStat, SkillDamageStat, SkillGemDef, SkillLevelDef, SkillStatSetDef,
    SkillStatSetLevel, StatSetDef, StatSetLabelDef, StatSetLabelsDef,
};
pub use tree::{
    PassiveAscendancy, PassiveClass, PassiveNodeDef, PassiveNodeKind, PassiveNodeVariant,
    PassiveTreeMeta,
};
pub use triggers::{
    MirageConfigDef, MirageConfigsDef, MirageSourceFilterDef, MirageTriggerDef, TriggerConfigDef,
    TriggerConfigsDef, TriggerKeyDef, TriggerSkillCondDef,
};
pub use unarmed_data::{UnarmedDataTable, UnarmedWeaponDef};
pub use vendor_name_aliases::{
    VENDOR_NAME_ALIASES_SCHEMA, VendorNameAliasDef, VendorNameAliasesDoc,
};
pub use weapon_types::{WeaponTypeDef, WeaponTypeTable};
